### ISSUE TITLE
2D chart ValueError: 'center right' is not a valid value for align; supported values are 'center', 'right', 'left'

### ISSUE THREAD

**Issue by jodykpw** [louwrentius/fio-plot#24]
./fio_plot -i ../benchmark_script/benchmarks/sda1/4k/ -T "Title" -s https://louwrentius.com -l -n 1 -r randread

Traceback (most recent call last):
  File "./fio_plot", line 141, in <module>
    main()
  File "./fio_plot", line 129, in main
    uses_json_files[item](settings, parsed_data)
  File "/scripts/fio-plot/fio_plot/fiolib/bar2d.py", line 62, in chart_2dbarchart_jsonlogdata
    shared.create_stddev_table(data, ax2)
  **File "/scripts/fio-plot/fio_plot/fiolib/shared_chart.py", line 153**, in create_stddev_table
    rasterized=False)
  File "/usr/local/lib64/python3.6/site-packages/matplotlib/table.py", line 802, in table
    loc=cellLoc)
  File "/usr/local/lib64/python3.6/site-packages/matplotlib/table.py", line 337, in add_cell
    cell = Cell(xy, visible_edges=self.edges, *args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/matplotlib/table.py", line 99, in __init__
    horizontalalignment=loc, verticalalignment='center')
  File "/usr/local/lib64/python3.6/site-packages/matplotlib/text.py", line 157, in __init__
    self.set_horizontalalignment(horizontalalignment)
  File "/usr/local/lib64/python3.6/site-packages/matplotlib/text.py", line 950, in set_horizontalalignment
    cbook._check_in_list(['center', 'right', 'left'], align=align)
  File "/usr/local/lib64/python3.6/site-packages/matplotlib/cbook/__init__.py", line 2250, in _check_in_list
    .format(v, k, ', '.join(map(repr, values))))
ValueError: '**center right**' is not a valid value for align; supported values are 'center', 'right', 'left'

Name: matplotlib
Version: 3.3.0
Summary: Python plotting package
Home-page: https://matplotlib.org
Author: John D. Hunter, Michael Droettboom
Author-email: matplotlib-users@python.org
License: PSF
Location: /usr/local/lib64/python3.6/site-packages
Requires: cycler, pillow, python-dateutil, pyparsing, numpy, kiwisolver

**Comment by jodykpw** [comment]
modified shared_chart.py

Line 152:
        cellLoc='center right', colWidths=[0.05] * cols,
To:
        cellLoc='right', colWidths=[0.05] * cols,

fixed the issue.

I'm not sure this is the right way to do.

**Comment by Martins3** [comment]
I came across the same issue too.

**Comment by louwrentius** [comment]
Thanks for the report. The graph is still wrong when applying this fix so I'll have to dig a bit deeper.

**Comment by louwrentius** [comment]
Any (significant) layout issues caused by the matplotlib 3.3.0 release should be fixed. Unfortunately, lower matplotlib versions are no longer supported.

**Comment by jodykpw** [comment]
Thank you for the update.

Suggestion
requirements.txt
numpy== 1.19.0
matplotlib== 3.3.0

**Comment by louwrentius** [comment]
I have updated requirements.txt as suggested. I'm closing this issue.
